### ISSUE TITLE
assemble-rss not in npm?

### ISSUE THREAD

**Issue by jfroom** [assemble/assemble-middleware-rss#1]
I'm getting the following error when trying to install this plugin. Thanks.

```
 ⌘ npm install assemble-rss --save-dev                                                                                         1 ↵
npm http GET https://registry.npmjs.org/assemble-rss
npm http 404 https://registry.npmjs.org/assemble-rss
npm ERR! 404 'assemble-rss' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.
```

**Comment by jonschlinkert** [comment]
Sorry, I must have accidentally removed the notice, but this project isn't ready to be published and used. I haven't had had a chance to get it updated, but this is a good reminder

**Comment by jfroom** [comment]
Ok, I've started hand coding my rss file for my blog in the mean time. Thanks Jon.

**Comment by jonschlinkert** [comment]
Maybe I'll take a crack at getting a basic version pushed up, but I'd love to have some feedback on how it works out

**Comment by jfroom** [comment]
I'm sorry. I just noticed this at the very top 'NOT Published yet!' =] Don't kill yourself - I'll get by. Thanks.

**Comment by pburtchaell** [comment]
@jonschlinkert Hey Jon, what else needs to be done to get this up on npm? I may be able to help out.

**Comment by jonschlinkert** [comment]
Hey @pburtchaell! I'm not sure, it's been a while since I had time to look at it. You can own this plugin if you want. let me know and I'll add you to the repo

**Comment by pburtchaell** [comment]
Sure! I'll try and take a look at everything this weekend.

**Comment by pburtchaell** [comment]
Hey @jfroom if you are interested, feel free to test this out once I push up a working version.

**Comment by pburtchaell** [comment]
@jfroom I've released a working version of the plugin. If you are interested in testing it out, just install from npm `npm install assemble-middleware-rss`.
