### ISSUE TITLE
Add items to feed based off the date the item was published

### ISSUE THREAD

**Issue by pburtchaell** [assemble/assemble-middleware-rss#10]
Items are currently added to the feed in the order they are compiled by Assemble. This is an issue because the feed should be —in most cases— sorted by date. Thinking of making it a requirement to add a `date` to the YFM of each page and using that data to sort the pages.

**Comment by ashleynolan** [comment]
+1 for this enhancement – would definitely use this as currently the order of my feed is a bit all over the place
