### ISSUE TITLE
{{rss}} helper

### ISSUE THREAD

**Issue by pburtchaell** [assemble/assemble-middleware-rss#2]
- [ ] class name
- [ ] text link or icon. 
- [ ] automatically calculate path based on RSS feed

**Comment by jonschlinkert** [comment]
awesome! I'm happy to give pointers on anything in assemble if you need anything specific while you're working on this

**Comment by pburtchaell** [comment]
Hey @jonschlinkert could you remove "(NOT published yet!)" from the description? It is published and works —just needs some testing done.

**Comment by jonschlinkert** [comment]
done! thanks @pburtchaell!
