### ISSUE TITLE
Warning: Cannot read property 'name' of undefined 

### ISSUE THREAD

**Issue by nmattisson** [assemble/assemble-middleware-rss#9]
I'm trying to get this plugin up and running, and I'm new at JS so might very well be doing some basic errors. Basically, I just followed the readme, made an npm install and added the plugin to the assemble task.

Here is the relevant part of my gruntfile:

```
    grunt.initConfig({
        pkg: grunt.file.readJSON('./package.json'),
        assemble: {
            options: {
                layoutdir: './src/bonnet/layout/',
                assets: './dist/assets',
                helpers: './src/bonnet/helpers/**/*.js',
                collections: [{
                    name: 'posts',
                    sortby: 'posted',
                    sortorder: 'descending'
                }],
                plugins: ['assemble-middleware-rss'],
                rss: {
                    author: 'Author here',
                    title: 'RSS Feed Title',
                    description: 'RSS feed description.'
                },
            },
            pages: {
                files: [{
                    cwd: './src/content/',
                    dest: './dist/',
                    expand: true,
                    src: '**/*.md',
                }],
                options: {
                    layout: 'blogpost.hbs'  // This is the default layout. Special pages should specify layout in the md file.
                }
            },
        },
```

As soon as the module is loaded, I get this warning:

```
Warning: Cannot read property 'name' of undefined Use --force to continue.
```

Even if I just add the plugin and nothing else I still get the same error. I've also tried with different rss/feed options but always with the same result.

As you can tell, I'm a bit at a loss here. Let me know what I can do to help diagnose the error.

Thank you!

**Comment by pburtchaell** [comment]
Which version of the middleware are you using? There were several issues with v0.1.0.

**Comment by nmattisson** [comment]
```
"assemble-middleware-rss": "^0.2.5",
```

**Comment by pburtchaell** [comment]
Okay. Well it looks like the `author.name` property is undefined. To make sure this is defined properly, you need the author object in `package.json`, which is the source of this property:

```
"author": {
  "name": "My name",
  "email": "email@foo.com",
  "url": "mywebsite.com"
}
```

**Comment by nmattisson** [comment]
Thank you for your help! that seems to have solved that error, but unfortunately triggers another one.

While running the "assemble:pages" (assemble) task, I get the following warning:

```
Warning: Parameter 'url' must be a string, not undefined
```

The author object I copied verbatim from your suggestion. I also tried adding url to the blog posts, but this made no difference. Anything else I should try?

**Comment by nmattisson** [comment]
I got it to build by adding this to Package.json:

```
"homepage": "someurl.com",
```

I can see now that it's listed in the Readme, but it might not hurt to add it to the Quickstart section since it's needed to build. Thank you for your help!

**Comment by pburtchaell** [comment]
Great! I will update the docs to make this more clear.

**Comment by nmattisson** [comment]
Thanks @pburtchaell, your module is very appreciated!
